import java_cup.runtime.*;

terminal PLUS, TIMES, LPAREN, RPAREN;
terminal Integer NUMBER;

non terminal Integer expr, term, factor;

precedence left PLUS;
precedence left TIMES;

expr ::= expr:e PLUS term:t {: RESULT = new Integer(e.intValue() + t.intValue()); :} | term:t {: RESULT = t; :} ;
term ::= term:t TIMES factor:f {: RESULT = new Integer(t.intValue() * f.intValue()); :} | factor:f {: RESULT = f; :} ;
factor ::= LPAREN expr:e RPAREN {: RESULT = e; :} | NUMBER:n {: RESULT = n; :};